import { readFileSync } from 'node:fs'
import { effectiveCapabilityRegistry } from './visual-capability.mjs'

export const CAPABILITY_REGISTRY = JSON.parse(readFileSync(new URL('./capability-registry.json', import.meta.url), 'utf8'))
export const CANDIDATE_VERSION = 'agent-owned-planner.v1'
const object = (value) => value !== null && typeof value === 'object' && !Array.isArray(value)
const nonempty = (value) => typeof value === 'string' && value.trim().length > 0
const strings = { type: 'array', items: { type: 'string' } }
const text = { type: 'string' }
const shape = (properties, required = Object.keys(properties)) => ({ type: 'object', additionalProperties: false, properties, required })

// A planning schema, not a renderer payload schema. Trusted compilers own concrete blocks.
export const CANDIDATE_PLAN_SCHEMA = shape({
    version: { type: 'string', const: CANDIDATE_VERSION },
    title: text,
    description: text,
    choice: shape({
        playbookId: text,
        formationId: text,
        contract_version: text,
        rationale: text,
        requestedTypeStatus: { type: 'string', enum: ['absent', 'honoured', 'cannot_satisfy'] }
    }),
    subjectVisualNeed: shape({ disciplinaryDemand: text, whatToNotice: text, representationReason: text }),
    sections: {
        type: 'array',
        minItems: 1,
        maxItems: 24,
        items: shape({
            id: text,
            role: text,
            title: text,
            purpose: text,
            proseFocus: text,
            transitionPurpose: text,
            semanticStyle: { type: 'string', enum: CAPABILITY_REGISTRY.semanticStyles },
            blocks: {
                type: 'array',
                maxItems: 24,
                items: shape({
                    id: text,
                    capabilityId: { type: 'string', enum: CAPABILITY_REGISTRY.capabilities.map((item) => item.id) },
                    representationVariant: text,
                    purpose: text,
                    learnerAction: text,
                    resourceIds: strings,
                    anchor: shape({ whatToNotice: text, connectionToExplanation: text }),
                    fallback: shape({ capabilityId: text, condition: text }),
                    assessmentMode: { type: 'string', enum: ['none', 'instant_local', 'explicit_submit'] },
                    subtopicId: { type: ['integer', 'null'], minimum: 1 }
                })
            }
        })
    },
    resources: {
        type: 'array',
        maxItems: 24,
        items: shape({
            id: text,
            kind: { type: 'string', enum: ['image', 'video', 'numerical_data', 'calculation', 'source', 'document', 'canonical_subtopic'] },
            purpose: text,
            acquisitionBrief: text,
            dataNeeds: strings,
            providedEvidenceRefs: strings,
            illustrativeAllowed: { type: 'boolean' },
            required: { type: 'boolean' }
        })
    },
    videoBrief: {
        anyOf: [
            { type: 'null' },
            shape({
                objective: { type: 'string', maxLength: 240 },
                purpose: {
                    type: 'string',
                    enum: [
                        'concept_explanation',
                        'process_visualisation',
                        'worked_example',
                        'practical_demonstration',
                        'exam_technique',
                        'revision_recap'
                    ]
                },
                format: {
                    type: 'string',
                    enum: ['explanation', 'animation', 'demonstration', 'worked_example', 'exam_walkthrough', 'recap']
                },
                prerequisites: { type: 'string', maxLength: 100 },
                visualApproach: { type: 'string', maxLength: 120 },
                maxDurationSeconds: { type: 'integer', minimum: 60, maximum: 1800 }
            })
        ]
    },
    contractChangeNotes: strings
})

// Accept real released bundles. Formation IDs are copied, never generated by this module.
export function catalogueFromLiveContracts(live) {
    if (!object(live) || !Array.isArray(live.bundles)) throw new TypeError('Expected live-contracts bundles.')
    const playbookCatalogue = []
    const formationCatalogue = []
    for (const bundle of live.bundles) {
        const chunks = bundle.chunks ?? []
        const machine = chunks.find((chunk) => chunk.chunk_type === 'machine_contract')?.payload?.machine_contract ?? {}
        const guidance = chunks.find((chunk) => chunk.chunk_type === 'model_guidance')?.payload?.model_guidance ?? {}
        playbookCatalogue.push({
            id: bundle.id,
            version: bundle.release?.version ?? machine.playbook_version,
            situation: guidance.use_when ?? guidance.purpose ?? '',
            avoidWhen: guidance.avoid_when ?? '',
            assessmentPolicy: machine.assessment_policy ?? '',
            tokenMin: machine.token_min,
            tokenMax: machine.token_max,
            sectionMin: machine.section_min,
            sectionMax: machine.section_max,
            qualityRequirements: machine.quality_requirements ?? {}
        })
        const formations = chunks.find((chunk) => chunk.chunk_type === 'formation_manifests')?.payload?.formations ?? []
        for (const formation of formations) {
            const presentation = formation.presentation_contract ?? {}
            formationCatalogue.push({
                id: formation.formation_id,
                playbookId: bundle.id,
                version: bundle.release?.version ?? machine.playbook_version,
                situation: formation.suitable_learner_situation,
                requiredSectionSequence: formation.required_section_sequence,
                roleStyles: Object.fromEntries((presentation.html_section_roles ?? []).map((role) => [role.role, role.visual_variant])),
                compositionProfile: presentation.composition_profile,
                evidenceRequirements: formation.evidence_requirements,
                tokenHints: (formation.runtime_skeleton?.sections ?? []).map((section) => ({
                    role: section.role,
                    hint: section.token_hint
                })),
                closingPurpose: presentation.summary_pattern
            })
        }
    }
    return { playbookCatalogue, formationCatalogue }
}

function normalizeCatalogue(playbooks, formations) {
    if (!Array.isArray(playbooks) || !playbooks.length) throw new TypeError('Supply the approved experiment playbook catalogue.')
    if (!Array.isArray(formations) || !formations.length) throw new TypeError('Supply formations from the same experiment catalogue.')
    const p = playbooks.map((value) => ({
        ...value,
        id: value.id ?? value.playbook_id ?? value.playbookId,
        version: value.version ?? value.contract_version
    }))
    const f = formations.map((value) => ({
        ...value,
        id: value.id ?? value.formation_id ?? value.formationId,
        playbookId: value.playbookId ?? value.playbook_id,
        version: value.version ?? value.contract_version,
        requiredSectionSequence: value.requiredSectionSequence ?? value.required_section_sequence,
        situation: value.situation ?? value.suitable_learner_situation
    }))
    if (p.some((value) => !nonempty(value.id)) || new Set(p.map((value) => value.id)).size !== p.length)
        throw new TypeError('Playbook IDs must be real, nonempty and unique.')
    const ids = new Set(p.map((value) => value.id))
    if (f.some((value) => !nonempty(value.id) || !ids.has(value.playbookId) || !Array.isArray(value.requiredSectionSequence)))
        throw new TypeError('Each formation needs its catalogue ID, owning playbook and ordered section roles.')
    if (new Set(f.map((value) => `${value.playbookId}/${value.id}`)).size !== f.length)
        throw new TypeError('Duplicate formation within a playbook.')
    return { playbookCatalogue: p, formationCatalogue: f }
}

export function explicitStudentDocumentType(context) {
    const value = context?.requestedDocumentType
    const provenance = object(value) ? value.provenance : context?.requestedDocumentTypeProvenance
    const requested = object(value) ? value.value ?? value.type : value
    return nonempty(requested) && provenance?.source === 'student' && provenance.explicit === true ? requested.trim() : undefined
}

export function normalizePlannerContext(context) {
    if (!object(context) || !nonempty(context.objective)) throw new TypeError('A substantive objective is required.')
    const { requestedDocumentType, requestedDocumentTypeProvenance, playbookId, playbook_id, formationId, formation_id, ...brief } = context
    const explicitType = explicitStudentDocumentType(context)
    return {
        ...brief,
        objective: context.objective.trim(),
        outcome: context.outcome ?? context.intendedOutcome ?? '',
        substantiveContent: context.substantiveContent ?? '',
        planningSuggestions: context.planningSuggestions ?? [],
        ...(explicitType ? { requestedDocumentType: { value: explicitType, provenance: { source: 'student', explicit: true } } } : {})
    }
}

export function candidatePlanSchemaForRegistry(registry) {
    const schema = JSON.parse(JSON.stringify(CANDIDATE_PLAN_SCHEMA))
    schema.properties.sections.items.properties.blocks.items.properties.capabilityId.enum = registry.capabilities.map((item) => item.id)
    return schema
}

function compactCapabilities(registry) {
    return registry.capabilities.map(
        ({ id, blockType, purposes, families, dataNeeds, specializedOwner, interaction, assessment, fallback, anchoring }) => ({
            id,
            block: blockType,
            purposes,
            ...(families ? { families } : {}),
            needs: dataNeeds,
            owner: specializedOwner,
            interaction,
            assessment,
            fallback,
            anchor: anchoring
        })
    )
}

export function buildCandidatePlannerPrompt({ context, playbookCatalogue, formationCatalogue, registry = CAPABILITY_REGISTRY }) {
    registry = effectiveCapabilityRegistry(registry, context)
    const catalogue = normalizeCatalogue(playbookCatalogue, formationCatalogue)
    const brief = normalizePlannerContext(context)
    const system = `You are Tutor Today's Canvas learning-document planner. In ONE structured response, choose the best playbook and formation in the supplied experiment catalogue, then plan coherent ordered sections, purposeful representations, needed resources and semantic presentation. The catalogue may contain released contracts, explicitly approved research contracts or both; use their supplied IDs and contract versions. You own these choices; Toby supplies objective, intended outcome, substantive content and contextual evidence. Toby's planningSuggestions are advisory: adopt, adapt or reject them using their educational rationale. They are never a binding format or a student request.

Only a requestedDocumentType with explicit student provenance is an output constraint. Honour it within the suitable supplied structure, or report cannot_satisfy and explain the real conflict. Without it, independently choose the format. Use only supplied playbook/formation IDs and versions, copying the selected version to choice.contract_version. Preserve the chosen formation's required section-role order. Its token hints and preferred sequence are advisory, not a fixed fingerprint. An optional JEV shortlist may leave several eligible educational structures; evaluate them substantively rather than accept a forced family winner. Respect hard identity, assessment, size and count limits. If a fixed minimum or generic hint would force filler, report the precise contractChangeNotes; do not silently waive a contract or add decoration to hide the conflict.

Use only the supplied effective capabilities and exact family choices. Existing charts support bar, line, area and pie; richer chart grammars remain owned by their specialist compiler and require separate renderer integration. Relationship visuals retain their five approved designs. A template_diagram is available only when the server supplies an enabled, subject-reviewed template family. It complements existing tools for static structure, geometric inputs, simple forces and particle models. Never replace LaTeX, mathematical graphs, numerical charts, maps, chemical structures or sourced images with a generic diagram. No invented values, final area/formula, arbitrary labels or SVG; Homework uses hint/blank scaffolds and active independent assessment has no diagram coaching. Determine the disciplinary demand and what this student must notice. Each visual earns its place by explaining something that simpler prose would lose. Copy the exact registry family into representationVariant; use an empty string when a capability has no family choice. Use supplied learner evidence to choose the depth and support; do not infer a misconception, proficiency band or curriculum identifier that was not supplied.

Give each section one clear cognitive purpose, prerequisite order, concise explanation and a meaningful bridge. Preserve the supplied substantive scope across the document and finish the playbook's learning loop. Use approved semantic styles (concept/example/caution/practice/summary); trusted renderers own visual treatment. No CSS, executable code, arbitrary SVG, invented renderer schema or concrete unverified assets. Blocks plan intent, not visual payloads. A section can use prose only when it needs no token. Prefer fewer meaningful representations to repetitive layout fingerprints; there is no image/chart quota.

Anchor every representation explicitly: what to inspect, how it connects to this explanation and what action develops understanding. Gallery images need distinct roles and a matching numbered key. Charts need units, provenance or an illustrative-data label, sensible scales and uncertainty when relevant; point events are semantic values rather than coordinates. Mathematical graphs need domain/assumptions; chemical structures need view/edit intent. Video acquisitionBrief defines the ideal demonstration, the relevant moment and viewing question. Resource briefs must bind the exact evidence purpose; request search/calculation only where necessary and reuse supplied verified evidence refs.

PDFs are optional additional reading or practice only when materially useful for the selected guide: past papers, academic papers or educational readings. The main document must contain the educational content and achieve its objective without opening a PDF. A PDF resource has required=false. Its acquisitionBrief gives the purpose, expected level/board/edition when relevant, reading task or pages and a short actual-content review for appropriateness and usefulness. Keenable finds candidate links; Gemini reviews accessible actual content, not merely a title or URL. Do not invent a PDF link or treat an unread candidate as approved. Missing, inaccessible, inappropriate or late PDF evidence is dropped before publication, along with its token, optional heading and references. Keep the main learning sequence intact; never wait indefinitely, create an empty placeholder or require a repair solely to fill optional reading.

Distinguish local exploration, instant MCQ feedback, chemistry saves, conversational events and explicit assessed submission. Question Blocks require a supplied canonical positive subtopic ID, or a canonical_subtopic resolution resource and a blocked-until-resolved plan; never invent an ID. An unavailable assessed activity cannot silently become an untracked check. Expansion is presentation only and preserves state and document position. Every optional external resource needs a purpose-compatible fallback; report a missing required input rather than inventing evidence. Return compact JSON matching the schema including a concise learner-facing title and description; short rationales and resource briefs, no chain-of-thought. Keep the response within 2,600 completion tokens by using one concise sentence per prose focus and short specific anchoring clauses. Do not add another mandatory classifier or serial LLM stage.`
    const user = JSON.stringify({
        brief,
        playbooks: catalogue.playbookCatalogue,
        formations: catalogue.formationCatalogue,
        capabilities: compactCapabilities(registry),
        semanticStyles: registry.semanticStyles,
        presentationLimits: registry.presentation.budgets
    })
    return {
        system,
        user,
        messages: [
            { role: 'system', content: system },
            { role: 'user', content: user }
        ],
        responseSchema: candidatePlanSchemaForRegistry(registry),
        warnings:
            context.requestedDocumentType && !explicitStudentDocumentType(context)
                ? ['Removed requestedDocumentType without explicit student provenance. Carry Toby recommendations in planningSuggestions.']
                : []
    }
}

export function buildCandidatePlannerMessages(input) {
    return buildCandidatePlannerPrompt(input).messages
}

// Deterministic ownership/compatibility checks; teacher quality and provider schema checks remain distinct.
export function validateCandidatePlannerResult(result, { context, playbookCatalogue, formationCatalogue, registry = CAPABILITY_REGISTRY }) {
    registry = effectiveCapabilityRegistry(registry, context)
    const errors = [],
        warnings = []
    const catalogue = normalizeCatalogue(playbookCatalogue, formationCatalogue)
    if (!object(result)) return { valid: false, errors: ['Plan must be an object.'], warnings }
    if (result.version !== CANDIDATE_VERSION) errors.push('Unexpected plan version.')
    if (!nonempty(result.title) || !nonempty(result.description)) errors.push('Plan needs a learner-facing title and description.')
    const choice = result.choice ?? {}
    const playbook = catalogue.playbookCatalogue.find((item) => item.id === choice.playbookId)
    const formation = catalogue.formationCatalogue.find((item) => item.playbookId === choice.playbookId && item.id === choice.formationId)
    if (!playbook) errors.push('Unknown released playbook.')
    if (!formation) errors.push('Unknown formation for selected playbook.')
    const selectedVersion = formation?.version ?? playbook?.version
    if (!nonempty(selectedVersion) || choice.contract_version !== selectedVersion)
        errors.push('Selected contract_version must match the supplied catalogue.')
    const explicitType = explicitStudentDocumentType(context)
    if (!explicitType && choice.requestedTypeStatus !== 'absent') errors.push('Planner treated an unspecified format as a student request.')
    if (explicitType && !['honoured', 'cannot_satisfy'].includes(choice.requestedTypeStatus))
        errors.push('Explicit student document request was not addressed.')
    if (!nonempty(choice.rationale)) errors.push('Choice needs an educational rationale.')
    const sections = Array.isArray(result.sections) ? result.sections : []
    if (!sections.length) errors.push('Plan needs ordered sections.')
    if (formation && JSON.stringify(sections.map((section) => section.role)) !== JSON.stringify(formation.requiredSectionSequence))
        errors.push('Required formation role order was changed.')
    const capabilities = new Map(registry.capabilities.map((item) => [item.id, item]))
    const resources = Array.isArray(result.resources) ? result.resources : []
    const resourceIds = new Set(resources.map((item) => item.id))
    if (resourceIds.size !== resources.length || resources.some((item) => !nonempty(item.id)))
        errors.push('Resource IDs must be nonempty and unique.')
    const blockIds = new Set()
    let tokenCount = 0,
        visualCount = 0,
        diagramCount = 0
    for (const section of sections) {
        if (!registry.semanticStyles.includes(section.semanticStyle)) errors.push(`Unsupported semantic style in ${section.id}.`)
        if (!nonempty(section.purpose) || !nonempty(section.proseFocus))
            errors.push(`Section ${section.id} needs purpose and substantive explanation focus.`)
        for (const block of section.blocks ?? []) {
            if (!nonempty(block.id) || blockIds.has(block.id)) errors.push('Block IDs must be nonempty and unique.')
            blockIds.add(block.id)
            const capability = capabilities.get(block.capabilityId)
            if (!capability) {
                errors.push(`Unsupported capability ${block.capabilityId}.`)
                continue
            }
            if (capability.families && !capability.families.includes(block.representationVariant))
                errors.push(`Block ${block.id} needs an approved representation family.`)
            if (capability.blockType) tokenCount++
            if (capability.blockType === 'learning_visual') visualCount++
            if (capability.blockType === 'diagram') diagramCount++
            if (!nonempty(block.purpose) || !nonempty(block.anchor?.whatToNotice) || !nonempty(block.anchor?.connectionToExplanation))
                errors.push(`Block ${block.id} needs educational purpose and explicit anchoring.`)
            if (!capabilities.has(block.fallback?.capabilityId)) errors.push(`Block ${block.id} needs a registry fallback.`)
            if (!Array.isArray(block.resourceIds) || block.resourceIds.some((id) => !resourceIds.has(id)))
                errors.push(`Block ${block.id} references a missing resource.`)
            if (
                capability.id === 'pdf' &&
                (!block.resourceIds.length || block.resourceIds.some((id) => resources.find((r) => r.id === id)?.required !== false))
            )
                errors.push(`PDF ${block.id} must use optional reading resources.`)
            if (capability.id === 'question') {
                if (block.assessmentMode !== 'explicit_submit') errors.push(`Question ${block.id} must declare explicit submission.`)
                const canonicalId = Number.isSafeInteger(block.subtopicId) && block.subtopicId > 0
                const suppliedId = context?.canonicalSubtopicId ?? context?.subtopicId ?? context?.subtopic_id
                const resolution = resources.some((item) => item.kind === 'canonical_subtopic' && block.resourceIds?.includes(item.id))
                if (canonicalId && block.subtopicId !== suppliedId)
                    errors.push(`Question ${block.id} uses a curriculum ID not supplied as canonical context.`)
                if (!canonicalId && !resolution) errors.push(`Question ${block.id} requires canonical subtopic resolution.`)
                if (!canonicalId && resolution)
                    warnings.push(`Question ${block.id} cannot be authored/published until canonical resolution succeeds.`)
            } else if (block.assessmentMode === 'explicit_submit')
                errors.push(`Exploration block ${block.id} must not impersonate assessed submission.`)
        }
    }
    if (tokenCount > registry.presentation.budgets.maximumBlocks) errors.push('Plan exceeds Canvas block budget.')
    if (visualCount > registry.presentation.budgets.maximumLearningVisuals) errors.push('Plan exceeds relationship-visual count budget.')
    if (diagramCount > registry.presentation.budgets.maximumDiagrams) errors.push('Plan exceeds diagram count budget.')
    if (playbook?.tokenMin && tokenCount < playbook.tokenMin)
        warnings.push(
            `Current released token minimum ${playbook.tokenMin} is unmet; record the precise contract conflict rather than add filler.`
        )
    if (playbook?.tokenMax && tokenCount > playbook.tokenMax) errors.push('Plan exceeds selected playbook token maximum.')
    if (!nonempty(result.subjectVisualNeed?.disciplinaryDemand) || !nonempty(result.subjectVisualNeed?.whatToNotice))
        errors.push('Plan needs a subject-specific noticing/representation signal.')
    const prohibited = new Set(['css', 'javascript', 'jsx', 'rawSvg', 'rawSpec', 'visualSpec', 'rendererPayload'])
    function inspect(value) {
        if (Array.isArray(value)) return value.forEach(inspect)
        if (!object(value)) return
        for (const [key, child] of Object.entries(value)) {
            if (prohibited.has(key)) errors.push(`Planner emitted prohibited renderer field ${key}.`)
            inspect(child)
        }
    }
    inspect(result)
    return { valid: errors.length === 0, errors, warnings }
}
